In [43]:
import pandas as pd

In [44]:
crimes_df = pd.read_csv('Output/NPYD_Complaints_01-01-13_12-31-23_v2.csv')

In [45]:
crimes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280576 entries, 0 to 1280575
Data columns (total 7 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Complaint_No  1280576 non-null  object
 1   Reported_Dt   1280576 non-null  object
 2   Borough_Name  1280576 non-null  object
 3   Ofns_Desc     1280576 non-null  object
 4   Law_Cat       1280576 non-null  object
 5   Latitude      1280576 non-null  float64
 6   Longitude     1280576 non-null  float64
dtypes: float64(2), object(5)
memory usage: 68.4+ MB

In [46]:
# Update `Reported_Dt` to datetime
crimes_df['Reported_Dt'] = pd.to_datetime(crimes_df['Reported_Dt'])

# Sort DataFrame by the `Reported_Dt`
crimes_df = crimes_df.sort_values(by='Reported_Dt', ignore_index= True)

# Preview DataFrame
crimes_df.head(20)

,Complaint_No,Reported_Dt,Borough_Name,Ofns_Desc,Law_Cat,Latitude,Longitude
0,88397298,2013-01-01,MANHATTAN,VEHICLE AND TRAFFIC LAWS,MISDEMEANOR,40.848120,-73.930884
1,88378509,2013-01-01,MANHATTAN,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,40.784781,-73.977134
2,88378508,2013-01-01,MANHATTAN,INTOXICATED & IMPAIRED DRIVING,MISDEMEANOR,40.772209,-73.982179
3,88378506,2013-01-01,MANHATTAN,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,40.788597,-73.977179
4,88378505,2013-01-01,MANHATTAN,PETIT LARCENY,MISDEMEANOR,40.788597,-73.977179
5,88397294,2013-01-01,MANHATTAN,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,40.865107,-73.918447
6,88397297,2013-01-01,MANHATTAN,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,40.850452,-73.938469
7,88397307,2013-01-01,MANHATTAN,VEHICLE AND TRAFFIC LAWS,MISDEMEANOR,40.864462,-73.918943
8,88400523,2013-01-01,MANHATTAN,OFFENSES AGAINST PUBLIC ADMINI,MISDEMEANOR,40.799931,-73.940664
9,88378511,2013-01-01,MANHATTAN,PETIT LARCENY,MISDEMEANOR,40.785443,-73.977717
10,88378492,2013-01-01,MANHATTAN,GRAND LARCENY,FELONY,40.775300,-73.959703
11,88378488,2013-01-01,MANHATTAN,PETIT LARCENY,MISDEMEANOR,40.760544,-73.961295
12,88378487,2013-01-01,MANHATTAN,PETIT LARCENY,MISDEMEANOR,40.768430,-73.961548
13,88378486,2013-01-01,MANHATTAN,GRAND LARCENY,FELONY,40.779498,-73.955584
14,88378484,2013-01-01,MANHATTAN,HARRASSMENT 2,VIOLATION,40.761975,-73.986333
15,88378480,2013-01-01,MANHATTAN,PETIT LARCENY,MISDEMEANOR,40.762261,-73.987985
16,88378478,2013-01-01,MANHATTAN,GRAND LARCENY,FELONY,40.761258,-73.983656
17,88378474,2013-01-01,MANHATTAN,HARRASSMENT 2,VIOLATION,40.762184,-73.993611
18,88397034,2013-01-01,MANHATTAN,PETIT LARCENY,MISDEMEANOR,40.750423,-73.989280
19,88378489,2013-01-01,MANHATTAN,PETIT LARCENY,MISDEMEANOR,40.785586,-73.954308